# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'example-sdk-module' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for example-sdk-module
  pod 'Blockstack'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # target 'example-sdk-moduleTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  #   pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  #   pod 'react-native-radar', :path => '../node_modules/react-native-radar'

  #   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  #   pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  #   pod 'RNSecureStorage', :path => '../node_modules/react-native-secure-storage'

  #   pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  #   pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  #   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  #   pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  #   pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'


  #   pod 'RNFS', :path => '../node_modules/react-native-fs'

  #   pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  #   pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # end


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
